CREATE TABLE CORRIDAS_REALIZADAS (
    id_corrida INT PRIMARY KEY,
    categoria_carro VARCHAR(20),
    valor_corrida DECIMAL(10,2),
    forma_pagamento VARCHAR(20)
);

INSERT INTO CORRIDAS_REALIZADAS VALUES (1, 'Comfort', 25.00, 'Cartão');
INSERT INTO CORRIDAS_REALIZADAS VALUES (2, 'X', 15.00, 'Cartão');
INSERT INTO CORRIDAS_REALIZADAS VALUES (3, 'Black', 50.00, 'Cartão');
INSERT INTO CORRIDAS_REALIZADAS VALUES (4, 'Comfort', 30.00, 'Cartão');
INSERT INTO CORRIDAS_REALIZADAS VALUES (5, 'X', 12.00, 'Dinheiro');
INSERT INTO CORRIDAS_REALIZADAS VALUES (6, 'Black', 45.00, 'Cartão');
INSERT INTO CORRIDAS_REALIZADAS VALUES (7, 'Comfort', 28.00, 'Cartão');
INSERT INTO CORRIDAS_REALIZADAS VALUES (8, 'X', 18.00, 'Cartão');
